/** @type {import('jest').Config} */
module.exports = {
  displayName: 'pickup-app',
  preset: 'ts-jest/presets/default-esm',
  testEnvironment: 'jsdom',
  rootDir: '.',
  extensionsToTreatAsEsm: ['.ts', '.tsx'],
  setupFilesAfterEnv: ['<rootDir>/src/setupTests.ts'],
  testMatch: [
    '<rootDir>/src/**/*.test.ts',
    '<rootDir>/src/**/*.test.tsx',
    '<rootDir>/src/**/__tests__/**/*.ts',
    '<rootDir>/src/**/__tests__/**/*.tsx',
  ],
  collectCoverageFrom: [
    // UI allowlist
    'src/shared/ui/ScreenState.tsx',
    'src/shared/ui/ThemeSwitch.tsx',
    'src/shared/ui/surfacePrimitives.tsx',
    'src/shared/ui/ConfirmDialog/ConfirmDialog.tsx',
    'src/shared/ui/confirm/confirmApi.ts',
    'src/shared/ui/QuantityStepper.tsx',
    'src/shared/ui/OfflineBanner.tsx',
    'src/shared/ui/ClaimBadge.tsx',
    'src/shared/ui/QueueRow.tsx',
    'src/shared/ui/StatusBadge.tsx',
    'src/shared/ui/AlertBanner.tsx',
    'src/shared/ui/PickupBottomNav.tsx',
    'src/shared/ui/SearchField.tsx',
    'src/shared/ui/Input.tsx',
    'src/shared/ui/IconButton.tsx',
    // Money/staff logic
    'src/api/**/*.{ts,tsx}',
    'src/lib/**/*.{ts,tsx}',
    'src/features/queue/buildQueuePageViewModel.ts',
    'src/features/queue/queueAging.ts',
    'src/features/queue/useQueueScreen.ts',
    'src/features/queue/usePickupQueueSubscription.ts',
    'src/features/order/buildOrderPageViewModel.ts',
    'src/features/order/orderScreenMutations.ts',
    'src/features/scan/buildScanPageViewModel.ts',
    'src/features/sell/buildSellCatalogViewModel.ts',
    'src/features/sell/buildSellCartViewModel.ts',
    'src/features/sell/sellCartLogic.ts',
    'src/features/hub/buildStaffHubViewModel.ts',
    'src/features/barcode-assign/buildBarcodeAssignViewModel.ts',
    'src/features/barcode-assign/buildBarcodeAssignDetailViewModel.ts',
    '!src/**/*.d.ts',
    '!src/**/*.test.{ts,tsx}',
    '!src/**/__tests__/**',
    '!**/I*Ports.ts',
    '!**/I*Gateway.ts',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html', 'json-summary'],
  // Wave 6 + gap closure: money api at end-state 75/55/75/75 (measured ~99/94); else measured−2pp
  coverageThreshold: {
    './src/shared/ui/': { statements: 60, branches: 45, functions: 43, lines: 60 },
    './src/api/': { statements: 75, branches: 55, functions: 75, lines: 75 },
    './src/lib/': { statements: 80, branches: 60, functions: 65, lines: 80 },
    './src/features/queue/': { statements: 63, branches: 50, functions: 63, lines: 63 },
    './src/features/order/': { statements: 70, branches: 50, functions: 70, lines: 70 },
    './src/features/scan/': { statements: 70, branches: 50, functions: 70, lines: 70 },
    './src/features/sell/': { statements: 70, branches: 50, functions: 70, lines: 70 },
    './src/features/hub/': { statements: 70, branches: 50, functions: 70, lines: 70 },
    './src/features/barcode-assign/': { statements: 70, branches: 50, functions: 70, lines: 70 },
  },
  moduleNameMapper: {
    '^react$': '<rootDir>/node_modules/react',
    '^react-dom$': '<rootDir>/node_modules/react-dom',
    '^react/jsx-runtime$': '<rootDir>/node_modules/react/jsx-runtime',
    '^react/jsx-dev-runtime$': '<rootDir>/node_modules/react/jsx-dev-runtime',
    '^pi-kiosk-shared/ui$': '<rootDir>/../shared/src/ui/index.ts',
    '^pi-kiosk-shared/clientLogRedaction$':
      '<rootDir>/../shared/src/clientLogRedaction.ts',
    '^pi-kiosk-shared/logging$': '<rootDir>/../shared/src/logging/index.ts',
    '^pi-kiosk-shared/logging/(.*)$': '<rootDir>/../shared/src/logging/$1',
    '^pi-kiosk-shared/crossTab$': '<rootDir>/../shared/src/crossTab/index.ts',
    '^pi-kiosk-shared/sentry/captureRateLimitBreadcrumb$':
      '<rootDir>/../shared/src/sentry/captureRateLimitBreadcrumb.ts',
    '^pi-kiosk-shared/sentry/captureConflictBreadcrumb$':
      '<rootDir>/../shared/src/sentry/captureConflictBreadcrumb.ts',
    '^pi-kiosk-shared/sentry$': '<rootDir>/../shared/src/sentry/initSentry.ts',
    '^pi-kiosk-shared$': '<rootDir>/../shared/src/index.ts',
    '^@marsidev/react-turnstile$':
      '<rootDir>/src/test/shims/react-turnstile.shim.tsx',
    '^.*/readViteMetaEnv(\\.js)?$': '<rootDir>/src/test/shims/readViteMetaEnv.shim.ts',
    '^(\\.{1,2}/.*)\\.js$': '$1',
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
    '^(.*/)?test/e2e/errorIsolationProbe(\\.js)?$':
      '<rootDir>/src/test/shims/errorIsolationProbe.shim.tsx',
    '<rootDir>/src/test/e2e/errorIsolationProbe.ts':
      '<rootDir>/src/test/shims/errorIsolationProbe.shim.tsx',
    '<rootDir>/src/test/e2e/errorIsolationProbe.js':
      '<rootDir>/src/test/shims/errorIsolationProbe.shim.tsx',
  },
  testPathIgnorePatterns: [
    '/node_modules/',
  ],
  transform: {
    '^.+\\.(ts|tsx|js)$': ['ts-jest', { useESM: true, tsconfig: 'tsconfig.json' }],
  },
  transformIgnorePatterns: [
    'node_modules/(?!(pi-kiosk-shared|@marsidev)/)',
  ],
};
